import { Component } from '@angular/core';

@Component({
  selector: 'app-placementsummary',
  templateUrl: './placementsummary.component.html',
  styleUrls: ['./placementsummary.component.css']
})
export class PlacementsummaryComponent {
  driveData = [
    {
      DriveType: 'Drive Type',
      Eligible: 853,
      Registred: 301,
      Participated: 199,
      NotParticipated: 0,
      AttendanceNotUploaded: 102,
      Selected: 3,
      OfferAccepted: 1,
      OfferRejected: 3,
      UpcomingDrives: 197,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'COMPETETIVE EVENT',
      Eligible: 110,
      Registred: 13,
      Participated: 0,
      NotParticipated: 0,
      AttendanceNotUploaded: 13,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 0,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Full Term Internship',
      Eligible: 86,
      Registred: 46,
      Participated: 41,
      NotParticipated: 0,
      AttendanceNotUploaded: 5,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 41,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Guest Lecture',
      Eligible: 2,
      Registred: 2,
      Participated: 2,
      NotParticipated: 0,
      AttendanceNotUploaded: 0,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 0,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Information Notice',
      Eligible: 18,
      Registred: 6,
      Participated: 0,
      NotParticipated: 0,
      AttendanceNotUploaded: 6,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 0,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Live Project',
      Eligible: 1,
      Registred: 1,
      Participated: 1,
      NotParticipated: 0,
      AttendanceNotUploaded: 0,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 1,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'OFF CAMPUS Drive',
      Eligible: 12,
      Registred: 1,
      Participated: 0,
      NotParticipated: 0,
      AttendanceNotUploaded: 1,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 0,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'ON CAMPUS Drive',
      Eligible: 481,
      Registred: 172,
      Participated: 105,
      NotParticipated: 0,
      AttendanceNotUploaded: 67,
      Selected: 2,
      OfferAccepted: 1,
      OfferRejected: 1,
      UpcomingDrives: 2,
      ResultDeclared: 105,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'One-year Internship',
      Eligible: 95,
      Registred: 54,
      Participated: 48,
      NotParticipated: 0,
      AttendanceNotUploaded: 6,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 48,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Summer Internship',
      Eligible: 2,
      Registred: 1,
      Participated: 1,
      NotParticipated: 0,
      AttendanceNotUploaded: 0,
      Selected: 1,
      OfferAccepted: 0,
      OfferRejected: 0,
      UpcomingDrives: 1,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Training Cum Drive',
      Eligible: 46,
      Registred: 5,
      Participated: 1,
      NotParticipated: 0,
      AttendanceNotUploaded: 4,
      Selected: 0,
      OfferAccepted: 0,
      OfferRejected: 1,
      UpcomingDrives: 1,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    },
    {
      DriveType: 'Total',
      Eligible: 853,
      Registred: 301,
      Participated: 199,
      NotParticipated: 0,
      AttendanceNotUploaded: 102,
      Selected: 3,
      OfferAccepted: 1,
      OfferRejected: 3,
      UpcomingDrives: 197,
      ResultDeclared: 0,
      ResultNotDeclared: 0,
      FineImposed: 0
    }
    
  ];
 
}

